// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: raft_messages.proto

#include "raft_messages.pb.h"
#include "raft_messages.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace raft_messages {

static const char* RaftMessages_method_names[] = {
  "/raft_messages.RaftMessages/RequestVote",
  "/raft_messages.RaftMessages/AppendEntries",
  "/raft_messages.RaftMessages/InstallSnapshot",
};

std::unique_ptr< RaftMessages::Stub> RaftMessages::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RaftMessages::Stub> stub(new RaftMessages::Stub(channel, options));
  return stub;
}

RaftMessages::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RequestVote_(RaftMessages_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AppendEntries_(RaftMessages_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_InstallSnapshot_(RaftMessages_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RaftMessages::Stub::RequestVote(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest& request, ::raft_messages::RequestVoteResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RequestVote_, context, request, response);
}

void RaftMessages::Stub::async::RequestVote(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest* request, ::raft_messages::RequestVoteResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestVote_, context, request, response, std::move(f));
}

void RaftMessages::Stub::async::RequestVote(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest* request, ::raft_messages::RequestVoteResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestVote_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::raft_messages::RequestVoteResponse>* RaftMessages::Stub::PrepareAsyncRequestVoteRaw(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::raft_messages::RequestVoteResponse, ::raft_messages::RequestVoteRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RequestVote_, context, request);
}

::grpc::ClientAsyncResponseReader< ::raft_messages::RequestVoteResponse>* RaftMessages::Stub::AsyncRequestVoteRaw(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRequestVoteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RaftMessages::Stub::AppendEntries(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest& request, ::raft_messages::AppendEntriesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AppendEntries_, context, request, response);
}

void RaftMessages::Stub::async::AppendEntries(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest* request, ::raft_messages::AppendEntriesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AppendEntries_, context, request, response, std::move(f));
}

void RaftMessages::Stub::async::AppendEntries(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest* request, ::raft_messages::AppendEntriesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AppendEntries_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::raft_messages::AppendEntriesResponse>* RaftMessages::Stub::PrepareAsyncAppendEntriesRaw(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::raft_messages::AppendEntriesResponse, ::raft_messages::AppendEntriesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AppendEntries_, context, request);
}

::grpc::ClientAsyncResponseReader< ::raft_messages::AppendEntriesResponse>* RaftMessages::Stub::AsyncAppendEntriesRaw(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAppendEntriesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RaftMessages::Stub::InstallSnapshot(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest& request, ::raft_messages::InstallSnapshotResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_InstallSnapshot_, context, request, response);
}

void RaftMessages::Stub::async::InstallSnapshot(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest* request, ::raft_messages::InstallSnapshotResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_InstallSnapshot_, context, request, response, std::move(f));
}

void RaftMessages::Stub::async::InstallSnapshot(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest* request, ::raft_messages::InstallSnapshotResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_InstallSnapshot_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::raft_messages::InstallSnapshotResponse>* RaftMessages::Stub::PrepareAsyncInstallSnapshotRaw(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::raft_messages::InstallSnapshotResponse, ::raft_messages::InstallSnapshotRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_InstallSnapshot_, context, request);
}

::grpc::ClientAsyncResponseReader< ::raft_messages::InstallSnapshotResponse>* RaftMessages::Stub::AsyncInstallSnapshotRaw(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncInstallSnapshotRaw(context, request, cq);
  result->StartCall();
  return result;
}

RaftMessages::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RaftMessages_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RaftMessages::Service, ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RaftMessages::Service* service,
             ::grpc::ServerContext* ctx,
             const ::raft_messages::RequestVoteRequest* req,
             ::raft_messages::RequestVoteResponse* resp) {
               return service->RequestVote(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RaftMessages_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RaftMessages::Service, ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RaftMessages::Service* service,
             ::grpc::ServerContext* ctx,
             const ::raft_messages::AppendEntriesRequest* req,
             ::raft_messages::AppendEntriesResponse* resp) {
               return service->AppendEntries(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RaftMessages_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RaftMessages::Service, ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RaftMessages::Service* service,
             ::grpc::ServerContext* ctx,
             const ::raft_messages::InstallSnapshotRequest* req,
             ::raft_messages::InstallSnapshotResponse* resp) {
               return service->InstallSnapshot(ctx, req, resp);
             }, this)));
}

RaftMessages::Service::~Service() {
}

::grpc::Status RaftMessages::Service::RequestVote(::grpc::ServerContext* context, const ::raft_messages::RequestVoteRequest* request, ::raft_messages::RequestVoteResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RaftMessages::Service::AppendEntries(::grpc::ServerContext* context, const ::raft_messages::AppendEntriesRequest* request, ::raft_messages::AppendEntriesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RaftMessages::Service::InstallSnapshot(::grpc::ServerContext* context, const ::raft_messages::InstallSnapshotRequest* request, ::raft_messages::InstallSnapshotResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* RaftStreamMessages_method_names[] = {
  "/raft_messages.RaftStreamMessages/RequestVote",
  "/raft_messages.RaftStreamMessages/AppendEntries",
  "/raft_messages.RaftStreamMessages/InstallSnapshot",
};

std::unique_ptr< RaftStreamMessages::Stub> RaftStreamMessages::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RaftStreamMessages::Stub> stub(new RaftStreamMessages::Stub(channel, options));
  return stub;
}

RaftStreamMessages::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RequestVote_(RaftStreamMessages_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_AppendEntries_(RaftStreamMessages_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_InstallSnapshot_(RaftStreamMessages_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>* RaftStreamMessages::Stub::RequestVoteRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>::Create(channel_.get(), rpcmethod_RequestVote_, context);
}

void RaftStreamMessages::Stub::async::RequestVote(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::raft_messages::RequestVoteRequest,::raft_messages::RequestVoteResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::raft_messages::RequestVoteRequest,::raft_messages::RequestVoteResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_RequestVote_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>* RaftStreamMessages::Stub::AsyncRequestVoteRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>::Create(channel_.get(), cq, rpcmethod_RequestVote_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>* RaftStreamMessages::Stub::PrepareAsyncRequestVoteRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>::Create(channel_.get(), cq, rpcmethod_RequestVote_, context, false, nullptr);
}

::grpc::ClientReaderWriter< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>* RaftStreamMessages::Stub::AppendEntriesRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>::Create(channel_.get(), rpcmethod_AppendEntries_, context);
}

void RaftStreamMessages::Stub::async::AppendEntries(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::raft_messages::AppendEntriesRequest,::raft_messages::AppendEntriesResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::raft_messages::AppendEntriesRequest,::raft_messages::AppendEntriesResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_AppendEntries_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>* RaftStreamMessages::Stub::AsyncAppendEntriesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>::Create(channel_.get(), cq, rpcmethod_AppendEntries_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>* RaftStreamMessages::Stub::PrepareAsyncAppendEntriesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>::Create(channel_.get(), cq, rpcmethod_AppendEntries_, context, false, nullptr);
}

::grpc::ClientReaderWriter< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>* RaftStreamMessages::Stub::InstallSnapshotRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>::Create(channel_.get(), rpcmethod_InstallSnapshot_, context);
}

void RaftStreamMessages::Stub::async::InstallSnapshot(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::raft_messages::InstallSnapshotRequest,::raft_messages::InstallSnapshotResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::raft_messages::InstallSnapshotRequest,::raft_messages::InstallSnapshotResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_InstallSnapshot_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>* RaftStreamMessages::Stub::AsyncInstallSnapshotRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>::Create(channel_.get(), cq, rpcmethod_InstallSnapshot_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>* RaftStreamMessages::Stub::PrepareAsyncInstallSnapshotRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>::Create(channel_.get(), cq, rpcmethod_InstallSnapshot_, context, false, nullptr);
}

RaftStreamMessages::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RaftStreamMessages_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< RaftStreamMessages::Service, ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>(
          [](RaftStreamMessages::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::raft_messages::RequestVoteResponse,
             ::raft_messages::RequestVoteRequest>* stream) {
               return service->RequestVote(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RaftStreamMessages_method_names[1],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< RaftStreamMessages::Service, ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>(
          [](RaftStreamMessages::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::raft_messages::AppendEntriesResponse,
             ::raft_messages::AppendEntriesRequest>* stream) {
               return service->AppendEntries(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RaftStreamMessages_method_names[2],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< RaftStreamMessages::Service, ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>(
          [](RaftStreamMessages::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::raft_messages::InstallSnapshotResponse,
             ::raft_messages::InstallSnapshotRequest>* stream) {
               return service->InstallSnapshot(ctx, stream);
             }, this)));
}

RaftStreamMessages::Service::~Service() {
}

::grpc::Status RaftStreamMessages::Service::RequestVote(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::raft_messages::RequestVoteResponse, ::raft_messages::RequestVoteRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RaftStreamMessages::Service::AppendEntries(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::raft_messages::AppendEntriesResponse, ::raft_messages::AppendEntriesRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RaftStreamMessages::Service::InstallSnapshot(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::raft_messages::InstallSnapshotResponse, ::raft_messages::InstallSnapshotRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* kvserver_method_names[] = {
  "/raft_messages.kvserver/Get",
  "/raft_messages.kvserver/PutAppend",
};

std::unique_ptr< kvserver::Stub> kvserver::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< kvserver::Stub> stub(new kvserver::Stub(channel, options));
  return stub;
}

kvserver::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Get_(kvserver_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PutAppend_(kvserver_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status kvserver::Stub::Get(::grpc::ClientContext* context, const ::raft_messages::GetRequest& request, ::raft_messages::GetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::raft_messages::GetRequest, ::raft_messages::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Get_, context, request, response);
}

void kvserver::Stub::async::Get(::grpc::ClientContext* context, const ::raft_messages::GetRequest* request, ::raft_messages::GetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::raft_messages::GetRequest, ::raft_messages::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, std::move(f));
}

void kvserver::Stub::async::Get(::grpc::ClientContext* context, const ::raft_messages::GetRequest* request, ::raft_messages::GetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::raft_messages::GetResponse>* kvserver::Stub::PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::raft_messages::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::raft_messages::GetResponse, ::raft_messages::GetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Get_, context, request);
}

::grpc::ClientAsyncResponseReader< ::raft_messages::GetResponse>* kvserver::Stub::AsyncGetRaw(::grpc::ClientContext* context, const ::raft_messages::GetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status kvserver::Stub::PutAppend(::grpc::ClientContext* context, const ::raft_messages::PutAppendRequest& request, ::raft_messages::PutAppendResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::raft_messages::PutAppendRequest, ::raft_messages::PutAppendResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PutAppend_, context, request, response);
}

void kvserver::Stub::async::PutAppend(::grpc::ClientContext* context, const ::raft_messages::PutAppendRequest* request, ::raft_messages::PutAppendResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::raft_messages::PutAppendRequest, ::raft_messages::PutAppendResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PutAppend_, context, request, response, std::move(f));
}

void kvserver::Stub::async::PutAppend(::grpc::ClientContext* context, const ::raft_messages::PutAppendRequest* request, ::raft_messages::PutAppendResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PutAppend_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::raft_messages::PutAppendResponse>* kvserver::Stub::PrepareAsyncPutAppendRaw(::grpc::ClientContext* context, const ::raft_messages::PutAppendRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::raft_messages::PutAppendResponse, ::raft_messages::PutAppendRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PutAppend_, context, request);
}

::grpc::ClientAsyncResponseReader< ::raft_messages::PutAppendResponse>* kvserver::Stub::AsyncPutAppendRaw(::grpc::ClientContext* context, const ::raft_messages::PutAppendRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPutAppendRaw(context, request, cq);
  result->StartCall();
  return result;
}

kvserver::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      kvserver_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< kvserver::Service, ::raft_messages::GetRequest, ::raft_messages::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](kvserver::Service* service,
             ::grpc::ServerContext* ctx,
             const ::raft_messages::GetRequest* req,
             ::raft_messages::GetResponse* resp) {
               return service->Get(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      kvserver_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< kvserver::Service, ::raft_messages::PutAppendRequest, ::raft_messages::PutAppendResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](kvserver::Service* service,
             ::grpc::ServerContext* ctx,
             const ::raft_messages::PutAppendRequest* req,
             ::raft_messages::PutAppendResponse* resp) {
               return service->PutAppend(ctx, req, resp);
             }, this)));
}

kvserver::Service::~Service() {
}

::grpc::Status kvserver::Service::Get(::grpc::ServerContext* context, const ::raft_messages::GetRequest* request, ::raft_messages::GetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status kvserver::Service::PutAppend(::grpc::ServerContext* context, const ::raft_messages::PutAppendRequest* request, ::raft_messages::PutAppendResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace raft_messages

