// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: raft_messages.proto
#ifndef GRPC_raft_5fmessages_2eproto__INCLUDED
#define GRPC_raft_5fmessages_2eproto__INCLUDED

#include "raft_messages.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace raft_messages {

class RaftMessages final {
 public:
  static constexpr char const* service_full_name() {
    return "raft_messages.RaftMessages";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RequestVote(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest& request, ::raft_messages::RequestVoteResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::RequestVoteResponse>> AsyncRequestVote(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::RequestVoteResponse>>(AsyncRequestVoteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::RequestVoteResponse>> PrepareAsyncRequestVote(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::RequestVoteResponse>>(PrepareAsyncRequestVoteRaw(context, request, cq));
    }
    virtual ::grpc::Status AppendEntries(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest& request, ::raft_messages::AppendEntriesResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::AppendEntriesResponse>> AsyncAppendEntries(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::AppendEntriesResponse>>(AsyncAppendEntriesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::AppendEntriesResponse>> PrepareAsyncAppendEntries(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::AppendEntriesResponse>>(PrepareAsyncAppendEntriesRaw(context, request, cq));
    }
    virtual ::grpc::Status InstallSnapshot(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest& request, ::raft_messages::InstallSnapshotResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::InstallSnapshotResponse>> AsyncInstallSnapshot(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::InstallSnapshotResponse>>(AsyncInstallSnapshotRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::InstallSnapshotResponse>> PrepareAsyncInstallSnapshot(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::InstallSnapshotResponse>>(PrepareAsyncInstallSnapshotRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void RequestVote(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest* request, ::raft_messages::RequestVoteResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RequestVote(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest* request, ::raft_messages::RequestVoteResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void AppendEntries(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest* request, ::raft_messages::AppendEntriesResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AppendEntries(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest* request, ::raft_messages::AppendEntriesResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void InstallSnapshot(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest* request, ::raft_messages::InstallSnapshotResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void InstallSnapshot(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest* request, ::raft_messages::InstallSnapshotResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::RequestVoteResponse>* AsyncRequestVoteRaw(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::RequestVoteResponse>* PrepareAsyncRequestVoteRaw(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::AppendEntriesResponse>* AsyncAppendEntriesRaw(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::AppendEntriesResponse>* PrepareAsyncAppendEntriesRaw(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::InstallSnapshotResponse>* AsyncInstallSnapshotRaw(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::InstallSnapshotResponse>* PrepareAsyncInstallSnapshotRaw(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RequestVote(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest& request, ::raft_messages::RequestVoteResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::RequestVoteResponse>> AsyncRequestVote(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::RequestVoteResponse>>(AsyncRequestVoteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::RequestVoteResponse>> PrepareAsyncRequestVote(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::RequestVoteResponse>>(PrepareAsyncRequestVoteRaw(context, request, cq));
    }
    ::grpc::Status AppendEntries(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest& request, ::raft_messages::AppendEntriesResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::AppendEntriesResponse>> AsyncAppendEntries(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::AppendEntriesResponse>>(AsyncAppendEntriesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::AppendEntriesResponse>> PrepareAsyncAppendEntries(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::AppendEntriesResponse>>(PrepareAsyncAppendEntriesRaw(context, request, cq));
    }
    ::grpc::Status InstallSnapshot(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest& request, ::raft_messages::InstallSnapshotResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::InstallSnapshotResponse>> AsyncInstallSnapshot(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::InstallSnapshotResponse>>(AsyncInstallSnapshotRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::InstallSnapshotResponse>> PrepareAsyncInstallSnapshot(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::InstallSnapshotResponse>>(PrepareAsyncInstallSnapshotRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RequestVote(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest* request, ::raft_messages::RequestVoteResponse* response, std::function<void(::grpc::Status)>) override;
      void RequestVote(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest* request, ::raft_messages::RequestVoteResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void AppendEntries(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest* request, ::raft_messages::AppendEntriesResponse* response, std::function<void(::grpc::Status)>) override;
      void AppendEntries(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest* request, ::raft_messages::AppendEntriesResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void InstallSnapshot(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest* request, ::raft_messages::InstallSnapshotResponse* response, std::function<void(::grpc::Status)>) override;
      void InstallSnapshot(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest* request, ::raft_messages::InstallSnapshotResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::raft_messages::RequestVoteResponse>* AsyncRequestVoteRaw(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::raft_messages::RequestVoteResponse>* PrepareAsyncRequestVoteRaw(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::raft_messages::AppendEntriesResponse>* AsyncAppendEntriesRaw(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::raft_messages::AppendEntriesResponse>* PrepareAsyncAppendEntriesRaw(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::raft_messages::InstallSnapshotResponse>* AsyncInstallSnapshotRaw(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::raft_messages::InstallSnapshotResponse>* PrepareAsyncInstallSnapshotRaw(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RequestVote_;
    const ::grpc::internal::RpcMethod rpcmethod_AppendEntries_;
    const ::grpc::internal::RpcMethod rpcmethod_InstallSnapshot_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RequestVote(::grpc::ServerContext* context, const ::raft_messages::RequestVoteRequest* request, ::raft_messages::RequestVoteResponse* response);
    virtual ::grpc::Status AppendEntries(::grpc::ServerContext* context, const ::raft_messages::AppendEntriesRequest* request, ::raft_messages::AppendEntriesResponse* response);
    virtual ::grpc::Status InstallSnapshot(::grpc::ServerContext* context, const ::raft_messages::InstallSnapshotRequest* request, ::raft_messages::InstallSnapshotResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RequestVote() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* /*context*/, const ::raft_messages::RequestVoteRequest* /*request*/, ::raft_messages::RequestVoteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequestVote(::grpc::ServerContext* context, ::raft_messages::RequestVoteRequest* request, ::grpc::ServerAsyncResponseWriter< ::raft_messages::RequestVoteResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AppendEntries() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* /*context*/, const ::raft_messages::AppendEntriesRequest* /*request*/, ::raft_messages::AppendEntriesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAppendEntries(::grpc::ServerContext* context, ::raft_messages::AppendEntriesRequest* request, ::grpc::ServerAsyncResponseWriter< ::raft_messages::AppendEntriesResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_InstallSnapshot() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* /*context*/, const ::raft_messages::InstallSnapshotRequest* /*request*/, ::raft_messages::InstallSnapshotResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInstallSnapshot(::grpc::ServerContext* context, ::raft_messages::InstallSnapshotRequest* request, ::grpc::ServerAsyncResponseWriter< ::raft_messages::InstallSnapshotResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RequestVote<WithAsyncMethod_AppendEntries<WithAsyncMethod_InstallSnapshot<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RequestVote() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::raft_messages::RequestVoteRequest* request, ::raft_messages::RequestVoteResponse* response) { return this->RequestVote(context, request, response); }));}
    void SetMessageAllocatorFor_RequestVote(
        ::grpc::MessageAllocator< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* /*context*/, const ::raft_messages::RequestVoteRequest* /*request*/, ::raft_messages::RequestVoteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RequestVote(
      ::grpc::CallbackServerContext* /*context*/, const ::raft_messages::RequestVoteRequest* /*request*/, ::raft_messages::RequestVoteResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AppendEntries() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::raft_messages::AppendEntriesRequest* request, ::raft_messages::AppendEntriesResponse* response) { return this->AppendEntries(context, request, response); }));}
    void SetMessageAllocatorFor_AppendEntries(
        ::grpc::MessageAllocator< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* /*context*/, const ::raft_messages::AppendEntriesRequest* /*request*/, ::raft_messages::AppendEntriesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AppendEntries(
      ::grpc::CallbackServerContext* /*context*/, const ::raft_messages::AppendEntriesRequest* /*request*/, ::raft_messages::AppendEntriesResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_InstallSnapshot() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::raft_messages::InstallSnapshotRequest* request, ::raft_messages::InstallSnapshotResponse* response) { return this->InstallSnapshot(context, request, response); }));}
    void SetMessageAllocatorFor_InstallSnapshot(
        ::grpc::MessageAllocator< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* /*context*/, const ::raft_messages::InstallSnapshotRequest* /*request*/, ::raft_messages::InstallSnapshotResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* InstallSnapshot(
      ::grpc::CallbackServerContext* /*context*/, const ::raft_messages::InstallSnapshotRequest* /*request*/, ::raft_messages::InstallSnapshotResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RequestVote<WithCallbackMethod_AppendEntries<WithCallbackMethod_InstallSnapshot<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RequestVote() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* /*context*/, const ::raft_messages::RequestVoteRequest* /*request*/, ::raft_messages::RequestVoteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AppendEntries() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* /*context*/, const ::raft_messages::AppendEntriesRequest* /*request*/, ::raft_messages::AppendEntriesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_InstallSnapshot() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* /*context*/, const ::raft_messages::InstallSnapshotRequest* /*request*/, ::raft_messages::InstallSnapshotResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RequestVote() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* /*context*/, const ::raft_messages::RequestVoteRequest* /*request*/, ::raft_messages::RequestVoteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequestVote(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AppendEntries() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* /*context*/, const ::raft_messages::AppendEntriesRequest* /*request*/, ::raft_messages::AppendEntriesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAppendEntries(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_InstallSnapshot() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* /*context*/, const ::raft_messages::InstallSnapshotRequest* /*request*/, ::raft_messages::InstallSnapshotResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInstallSnapshot(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RequestVote() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RequestVote(context, request, response); }));
    }
    ~WithRawCallbackMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* /*context*/, const ::raft_messages::RequestVoteRequest* /*request*/, ::raft_messages::RequestVoteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RequestVote(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AppendEntries() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AppendEntries(context, request, response); }));
    }
    ~WithRawCallbackMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* /*context*/, const ::raft_messages::AppendEntriesRequest* /*request*/, ::raft_messages::AppendEntriesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AppendEntries(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_InstallSnapshot() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->InstallSnapshot(context, request, response); }));
    }
    ~WithRawCallbackMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* /*context*/, const ::raft_messages::InstallSnapshotRequest* /*request*/, ::raft_messages::InstallSnapshotResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* InstallSnapshot(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RequestVote() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>* streamer) {
                       return this->StreamedRequestVote(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* /*context*/, const ::raft_messages::RequestVoteRequest* /*request*/, ::raft_messages::RequestVoteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRequestVote(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::raft_messages::RequestVoteRequest,::raft_messages::RequestVoteResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AppendEntries() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>* streamer) {
                       return this->StreamedAppendEntries(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* /*context*/, const ::raft_messages::AppendEntriesRequest* /*request*/, ::raft_messages::AppendEntriesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAppendEntries(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::raft_messages::AppendEntriesRequest,::raft_messages::AppendEntriesResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_InstallSnapshot() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>* streamer) {
                       return this->StreamedInstallSnapshot(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* /*context*/, const ::raft_messages::InstallSnapshotRequest* /*request*/, ::raft_messages::InstallSnapshotResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedInstallSnapshot(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::raft_messages::InstallSnapshotRequest,::raft_messages::InstallSnapshotResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RequestVote<WithStreamedUnaryMethod_AppendEntries<WithStreamedUnaryMethod_InstallSnapshot<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RequestVote<WithStreamedUnaryMethod_AppendEntries<WithStreamedUnaryMethod_InstallSnapshot<Service > > > StreamedService;
};

class RaftStreamMessages final {
 public:
  static constexpr char const* service_full_name() {
    return "raft_messages.RaftStreamMessages";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>> RequestVote(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>>(RequestVoteRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>> AsyncRequestVote(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>>(AsyncRequestVoteRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>> PrepareAsyncRequestVote(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>>(PrepareAsyncRequestVoteRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>> AppendEntries(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>>(AppendEntriesRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>> AsyncAppendEntries(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>>(AsyncAppendEntriesRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>> PrepareAsyncAppendEntries(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>>(PrepareAsyncAppendEntriesRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>> InstallSnapshot(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>>(InstallSnapshotRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>> AsyncInstallSnapshot(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>>(AsyncInstallSnapshotRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>> PrepareAsyncInstallSnapshot(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>>(PrepareAsyncInstallSnapshotRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void RequestVote(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::raft_messages::RequestVoteRequest,::raft_messages::RequestVoteResponse>* reactor) = 0;
      virtual void AppendEntries(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::raft_messages::AppendEntriesRequest,::raft_messages::AppendEntriesResponse>* reactor) = 0;
      virtual void InstallSnapshot(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::raft_messages::InstallSnapshotRequest,::raft_messages::InstallSnapshotResponse>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>* RequestVoteRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>* AsyncRequestVoteRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>* PrepareAsyncRequestVoteRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>* AppendEntriesRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>* AsyncAppendEntriesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>* PrepareAsyncAppendEntriesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>* InstallSnapshotRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>* AsyncInstallSnapshotRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>* PrepareAsyncInstallSnapshotRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>> RequestVote(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>>(RequestVoteRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>> AsyncRequestVote(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>>(AsyncRequestVoteRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>> PrepareAsyncRequestVote(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>>(PrepareAsyncRequestVoteRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>> AppendEntries(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>>(AppendEntriesRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>> AsyncAppendEntries(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>>(AsyncAppendEntriesRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>> PrepareAsyncAppendEntries(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>>(PrepareAsyncAppendEntriesRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>> InstallSnapshot(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>>(InstallSnapshotRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>> AsyncInstallSnapshot(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>>(AsyncInstallSnapshotRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>> PrepareAsyncInstallSnapshot(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>>(PrepareAsyncInstallSnapshotRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RequestVote(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::raft_messages::RequestVoteRequest,::raft_messages::RequestVoteResponse>* reactor) override;
      void AppendEntries(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::raft_messages::AppendEntriesRequest,::raft_messages::AppendEntriesResponse>* reactor) override;
      void InstallSnapshot(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::raft_messages::InstallSnapshotRequest,::raft_messages::InstallSnapshotResponse>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>* RequestVoteRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>* AsyncRequestVoteRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>* PrepareAsyncRequestVoteRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>* AppendEntriesRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>* AsyncAppendEntriesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>* PrepareAsyncAppendEntriesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>* InstallSnapshotRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>* AsyncInstallSnapshotRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>* PrepareAsyncInstallSnapshotRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RequestVote_;
    const ::grpc::internal::RpcMethod rpcmethod_AppendEntries_;
    const ::grpc::internal::RpcMethod rpcmethod_InstallSnapshot_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RequestVote(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::raft_messages::RequestVoteResponse, ::raft_messages::RequestVoteRequest>* stream);
    virtual ::grpc::Status AppendEntries(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::raft_messages::AppendEntriesResponse, ::raft_messages::AppendEntriesRequest>* stream);
    virtual ::grpc::Status InstallSnapshot(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::raft_messages::InstallSnapshotResponse, ::raft_messages::InstallSnapshotRequest>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RequestVote() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::raft_messages::RequestVoteResponse, ::raft_messages::RequestVoteRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequestVote(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::raft_messages::RequestVoteResponse, ::raft_messages::RequestVoteRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AppendEntries() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::raft_messages::AppendEntriesResponse, ::raft_messages::AppendEntriesRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAppendEntries(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::raft_messages::AppendEntriesResponse, ::raft_messages::AppendEntriesRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_InstallSnapshot() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::raft_messages::InstallSnapshotResponse, ::raft_messages::InstallSnapshotRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInstallSnapshot(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::raft_messages::InstallSnapshotResponse, ::raft_messages::InstallSnapshotRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(2, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RequestVote<WithAsyncMethod_AppendEntries<WithAsyncMethod_InstallSnapshot<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RequestVote() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->RequestVote(context); }));
    }
    ~WithCallbackMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::raft_messages::RequestVoteResponse, ::raft_messages::RequestVoteRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>* RequestVote(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AppendEntries() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackBidiHandler< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->AppendEntries(context); }));
    }
    ~WithCallbackMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::raft_messages::AppendEntriesResponse, ::raft_messages::AppendEntriesRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>* AppendEntries(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_InstallSnapshot() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackBidiHandler< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->InstallSnapshot(context); }));
    }
    ~WithCallbackMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::raft_messages::InstallSnapshotResponse, ::raft_messages::InstallSnapshotRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>* InstallSnapshot(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_RequestVote<WithCallbackMethod_AppendEntries<WithCallbackMethod_InstallSnapshot<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RequestVote() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::raft_messages::RequestVoteResponse, ::raft_messages::RequestVoteRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AppendEntries() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::raft_messages::AppendEntriesResponse, ::raft_messages::AppendEntriesRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_InstallSnapshot() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::raft_messages::InstallSnapshotResponse, ::raft_messages::InstallSnapshotRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RequestVote() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::raft_messages::RequestVoteResponse, ::raft_messages::RequestVoteRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequestVote(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AppendEntries() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::raft_messages::AppendEntriesResponse, ::raft_messages::AppendEntriesRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAppendEntries(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_InstallSnapshot() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::raft_messages::InstallSnapshotResponse, ::raft_messages::InstallSnapshotRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInstallSnapshot(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(2, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RequestVote() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->RequestVote(context); }));
    }
    ~WithRawCallbackMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::raft_messages::RequestVoteResponse, ::raft_messages::RequestVoteRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* RequestVote(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AppendEntries() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->AppendEntries(context); }));
    }
    ~WithRawCallbackMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::raft_messages::AppendEntriesResponse, ::raft_messages::AppendEntriesRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* AppendEntries(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_InstallSnapshot() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->InstallSnapshot(context); }));
    }
    ~WithRawCallbackMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::raft_messages::InstallSnapshotResponse, ::raft_messages::InstallSnapshotRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* InstallSnapshot(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

class kvserver final {
 public:
  static constexpr char const* service_full_name() {
    return "raft_messages.kvserver";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Get(::grpc::ClientContext* context, const ::raft_messages::GetRequest& request, ::raft_messages::GetResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::GetResponse>> AsyncGet(::grpc::ClientContext* context, const ::raft_messages::GetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::GetResponse>>(AsyncGetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::GetResponse>> PrepareAsyncGet(::grpc::ClientContext* context, const ::raft_messages::GetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::GetResponse>>(PrepareAsyncGetRaw(context, request, cq));
    }
    virtual ::grpc::Status PutAppend(::grpc::ClientContext* context, const ::raft_messages::PutAppendRequest& request, ::raft_messages::PutAppendResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::PutAppendResponse>> AsyncPutAppend(::grpc::ClientContext* context, const ::raft_messages::PutAppendRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::PutAppendResponse>>(AsyncPutAppendRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::PutAppendResponse>> PrepareAsyncPutAppend(::grpc::ClientContext* context, const ::raft_messages::PutAppendRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::PutAppendResponse>>(PrepareAsyncPutAppendRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Get(::grpc::ClientContext* context, const ::raft_messages::GetRequest* request, ::raft_messages::GetResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Get(::grpc::ClientContext* context, const ::raft_messages::GetRequest* request, ::raft_messages::GetResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void PutAppend(::grpc::ClientContext* context, const ::raft_messages::PutAppendRequest* request, ::raft_messages::PutAppendResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PutAppend(::grpc::ClientContext* context, const ::raft_messages::PutAppendRequest* request, ::raft_messages::PutAppendResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::GetResponse>* AsyncGetRaw(::grpc::ClientContext* context, const ::raft_messages::GetRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::GetResponse>* PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::raft_messages::GetRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::PutAppendResponse>* AsyncPutAppendRaw(::grpc::ClientContext* context, const ::raft_messages::PutAppendRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::PutAppendResponse>* PrepareAsyncPutAppendRaw(::grpc::ClientContext* context, const ::raft_messages::PutAppendRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Get(::grpc::ClientContext* context, const ::raft_messages::GetRequest& request, ::raft_messages::GetResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::GetResponse>> AsyncGet(::grpc::ClientContext* context, const ::raft_messages::GetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::GetResponse>>(AsyncGetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::GetResponse>> PrepareAsyncGet(::grpc::ClientContext* context, const ::raft_messages::GetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::GetResponse>>(PrepareAsyncGetRaw(context, request, cq));
    }
    ::grpc::Status PutAppend(::grpc::ClientContext* context, const ::raft_messages::PutAppendRequest& request, ::raft_messages::PutAppendResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::PutAppendResponse>> AsyncPutAppend(::grpc::ClientContext* context, const ::raft_messages::PutAppendRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::PutAppendResponse>>(AsyncPutAppendRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::PutAppendResponse>> PrepareAsyncPutAppend(::grpc::ClientContext* context, const ::raft_messages::PutAppendRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::PutAppendResponse>>(PrepareAsyncPutAppendRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Get(::grpc::ClientContext* context, const ::raft_messages::GetRequest* request, ::raft_messages::GetResponse* response, std::function<void(::grpc::Status)>) override;
      void Get(::grpc::ClientContext* context, const ::raft_messages::GetRequest* request, ::raft_messages::GetResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void PutAppend(::grpc::ClientContext* context, const ::raft_messages::PutAppendRequest* request, ::raft_messages::PutAppendResponse* response, std::function<void(::grpc::Status)>) override;
      void PutAppend(::grpc::ClientContext* context, const ::raft_messages::PutAppendRequest* request, ::raft_messages::PutAppendResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::raft_messages::GetResponse>* AsyncGetRaw(::grpc::ClientContext* context, const ::raft_messages::GetRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::raft_messages::GetResponse>* PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::raft_messages::GetRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::raft_messages::PutAppendResponse>* AsyncPutAppendRaw(::grpc::ClientContext* context, const ::raft_messages::PutAppendRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::raft_messages::PutAppendResponse>* PrepareAsyncPutAppendRaw(::grpc::ClientContext* context, const ::raft_messages::PutAppendRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Get_;
    const ::grpc::internal::RpcMethod rpcmethod_PutAppend_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Get(::grpc::ServerContext* context, const ::raft_messages::GetRequest* request, ::raft_messages::GetResponse* response);
    virtual ::grpc::Status PutAppend(::grpc::ServerContext* context, const ::raft_messages::PutAppendRequest* request, ::raft_messages::PutAppendResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Get() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::raft_messages::GetRequest* /*request*/, ::raft_messages::GetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGet(::grpc::ServerContext* context, ::raft_messages::GetRequest* request, ::grpc::ServerAsyncResponseWriter< ::raft_messages::GetResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PutAppend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PutAppend() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_PutAppend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutAppend(::grpc::ServerContext* /*context*/, const ::raft_messages::PutAppendRequest* /*request*/, ::raft_messages::PutAppendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPutAppend(::grpc::ServerContext* context, ::raft_messages::PutAppendRequest* request, ::grpc::ServerAsyncResponseWriter< ::raft_messages::PutAppendResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Get<WithAsyncMethod_PutAppend<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Get() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::raft_messages::GetRequest, ::raft_messages::GetResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::raft_messages::GetRequest* request, ::raft_messages::GetResponse* response) { return this->Get(context, request, response); }));}
    void SetMessageAllocatorFor_Get(
        ::grpc::MessageAllocator< ::raft_messages::GetRequest, ::raft_messages::GetResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::raft_messages::GetRequest, ::raft_messages::GetResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::raft_messages::GetRequest* /*request*/, ::raft_messages::GetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Get(
      ::grpc::CallbackServerContext* /*context*/, const ::raft_messages::GetRequest* /*request*/, ::raft_messages::GetResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_PutAppend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PutAppend() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::raft_messages::PutAppendRequest, ::raft_messages::PutAppendResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::raft_messages::PutAppendRequest* request, ::raft_messages::PutAppendResponse* response) { return this->PutAppend(context, request, response); }));}
    void SetMessageAllocatorFor_PutAppend(
        ::grpc::MessageAllocator< ::raft_messages::PutAppendRequest, ::raft_messages::PutAppendResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::raft_messages::PutAppendRequest, ::raft_messages::PutAppendResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_PutAppend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutAppend(::grpc::ServerContext* /*context*/, const ::raft_messages::PutAppendRequest* /*request*/, ::raft_messages::PutAppendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PutAppend(
      ::grpc::CallbackServerContext* /*context*/, const ::raft_messages::PutAppendRequest* /*request*/, ::raft_messages::PutAppendResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Get<WithCallbackMethod_PutAppend<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Get() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::raft_messages::GetRequest* /*request*/, ::raft_messages::GetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PutAppend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PutAppend() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_PutAppend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutAppend(::grpc::ServerContext* /*context*/, const ::raft_messages::PutAppendRequest* /*request*/, ::raft_messages::PutAppendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Get() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::raft_messages::GetRequest* /*request*/, ::raft_messages::GetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGet(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_PutAppend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PutAppend() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_PutAppend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutAppend(::grpc::ServerContext* /*context*/, const ::raft_messages::PutAppendRequest* /*request*/, ::raft_messages::PutAppendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPutAppend(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Get() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Get(context, request, response); }));
    }
    ~WithRawCallbackMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::raft_messages::GetRequest* /*request*/, ::raft_messages::GetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Get(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PutAppend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PutAppend() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PutAppend(context, request, response); }));
    }
    ~WithRawCallbackMethod_PutAppend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutAppend(::grpc::ServerContext* /*context*/, const ::raft_messages::PutAppendRequest* /*request*/, ::raft_messages::PutAppendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PutAppend(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Get() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::raft_messages::GetRequest, ::raft_messages::GetResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::raft_messages::GetRequest, ::raft_messages::GetResponse>* streamer) {
                       return this->StreamedGet(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::raft_messages::GetRequest* /*request*/, ::raft_messages::GetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGet(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::raft_messages::GetRequest,::raft_messages::GetResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PutAppend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PutAppend() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::raft_messages::PutAppendRequest, ::raft_messages::PutAppendResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::raft_messages::PutAppendRequest, ::raft_messages::PutAppendResponse>* streamer) {
                       return this->StreamedPutAppend(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PutAppend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PutAppend(::grpc::ServerContext* /*context*/, const ::raft_messages::PutAppendRequest* /*request*/, ::raft_messages::PutAppendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPutAppend(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::raft_messages::PutAppendRequest,::raft_messages::PutAppendResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Get<WithStreamedUnaryMethod_PutAppend<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Get<WithStreamedUnaryMethod_PutAppend<Service > > StreamedService;
};

}  // namespace raft_messages


#endif  // GRPC_raft_5fmessages_2eproto__INCLUDED
